const BACKEND_BASE_URL = "http://localhost:8080";
const BACKEND_ADMIN_SERVER_BASE_URL = "http://localhost:9090";
const BACKEND_LOGIN_SERVER_BASE_URL = "http://localhost:8888";
const LOGIN_PAGE_URL = "/";

const MODE_NO_OPP = 0;
const MODE_SEARCH = 1;
const MODE_FILTER_BY_GENRE = 2;
const MODE_FILTER_BY_LANGUAGE = 3;
const MODE_FILTER_BY_PRICE_RANGE = 4;
const MODE_SORT_BY_PRICE_HL = 5;
const MODE_SORT_BY_PRICE_LH = 6;
const MODE_SORT_BY_DATE_OF_RELEASE = 7;

const GENRES = [
    "All",
    "Fantasy",
    "Adventure",
    "Romance",
    "Contemporary",
    "Dystopian",
    "Mystery",
    "Horror",
    "Thriller",
    "Paranormal",
    "Historical fiction",
    "Science Fiction",
    "Children’s",
    "Memoir",
    "Cooking",
    "Art",
    "Self-help / Personal",
    "Development",
    "Motivational",
    "Health",
    "History",
    "Travel",
    "Guide / How-to",
    "Families & Relationships",
    "Humor"
];


const LANGUAGES = [
    "All",
    "Abkhaz",
    "Afar",
    "Afrikaans",
    "Akan",
    "Albanian",
    "Amharic",
    "Arabic",
    "Aragonese",
    "Armenian",
    "Assamese",
    "Avaric",
    "Avestan",
    "Aymara",
    "Azerbaijani",
    "Bambara",
    "Bashkir",
    "Basque",
    "Belarusian",
    "Bengali",
    "Bihari",
    "Bislama",
    "Bosnian",
    "Breton",
    "Bulgarian",
    "Burmese",
    "Catalan; Valencian",
    "Chamorro",
    "Chechen",
    "Chichewa; Chewa; Nyanja",
    "Chinese",
    "Chuvash",
    "Cornish",
    "Corsican",
    "Cree",
    "Croatian",
    "Czech",
    "Danish",
    "Divehi; Dhivehi; Maldivian;",
    "Dutch",
    "English",
    "Esperanto",
    "Estonian",
    "Ewe",
    "Faroese",
    "Fijian",
    "Finnish",
    "French",
    "Fula; Fulah; Pulaar; Pular",
    "Galician",
    "Georgian",
    "German",
    "Greek, Modern",
    "Guaraní",
    "Gujarati",
    "Haitian; Haitian Creole",
    "Hausa",
    "Hebrew",
    "Herero",
    "Hindi",
    "Hiri Motu",
    "Hungarian",
    "Interlingua",
    "Indonesian",
    "Interlingue",
    "Irish",
    "Igbo",
    "Inupiaq",
    "Ido",
    "Icelandic",
    "Italian",
    "Inuktitut",
    "Japanese",
    "Javanese",
    "Kalaallisut, Greenlandic",
    "Kannada",
    "Kanuri",
    "Kashmiri",
    "Kazakh",
    "Khmer",
    "Kikuyu, Gikuyu",
    "Kinyarwanda",
    "Kirghiz, Kyrgyz",
    "Komi",
    "Kongo",
    "Korean",
    "Kurdish",
    "Kwanyama, Kuanyama",
    "Latin",
    "Luxembourgish, Letzeburgesch",
    "Luganda",
    "Limburgish, Limburgan, Limburger",
    "Lingala",
    "Lao",
    "Lithuanian",
    "Luba-Katanga",
    "Latvian",
    "Manx",
    "Macedonian",
    "Malagasy",
    "Malay",
    "Malayalam",
    "Maltese",
    "Māori",
    "Marathi (Marāṭhī)",
    "Marshallese",
    "Mongolian",
    "Nauru",
    "Navajo, Navaho",
    "Norwegian Bokmål",
    "North Ndebele",
    "Nepali",
    "Ndonga",
    "Norwegian Nynorsk",
    "Norwegian",
    "Nuosu",
    "South Ndebele",
    "Occitan",
    "Ojibwe, Ojibwa",
    "Oromo",
    "Oriya",
    "Ossetian, Ossetic",
    "Panjabi, Punjabi",
    "Pāli",
    "Persian",
    "Polish",
    "Pashto, Pushto",
    "Portuguese",
    "Quechua",
    "Romansh",
    "Kirundi",
    "Romanian, Moldavian, Moldovan",
    "Russian",
    "Sanskrit (Saṁskṛta)",
    "Sardinian",
    "Sindhi",
    "Northern Sami",
    "Samoan",
    "Sango",
    "Serbian",
    "Scottish Gaelic; Gaelic",
    "Shona",
    "Sinhala, Sinhalese",
    "Slovak",
    "Slovene",
    "Somali",
    "Southern Sotho",
    "Spanish; Castilian",
    "Sundanese",
    "Swahili",
    "Swati",
    "Swedish",
    "Tamil",
    "Telugu",
    "Tajik",
    "Thai",
    "Tigrinya",
    "Tibetan Standard, Tibetan, Central",
    "Turkmen",
    "Tagalog",
    "Tswana",
    "Tonga (Tonga Islands)",
    "Turkish",
    "Tsonga",
    "Tatar",
    "Twi",
    "Tahitian",
    "Uighur, Uyghur",
    "Ukrainian",
    "Urdu",
    "Uzbek",
    "Venda",
    "Vietnamese",
    "Volapük",
    "Walloon",
    "Welsh",
    "Wolof",
    "Western Frisian",
    "Xhosa",
    "Yiddish",
    "Yoruba",
    "Zhuang, Chuang"
];

export {
    BACKEND_BASE_URL,
    BACKEND_ADMIN_SERVER_BASE_URL,
    BACKEND_LOGIN_SERVER_BASE_URL,
    GENRES,
    LANGUAGES,
    LOGIN_PAGE_URL,
    MODE_NO_OPP,
    MODE_SEARCH,
    MODE_FILTER_BY_GENRE,
    MODE_FILTER_BY_LANGUAGE,
    MODE_FILTER_BY_PRICE_RANGE,
    MODE_SORT_BY_PRICE_HL,
    MODE_SORT_BY_PRICE_LH,
    MODE_SORT_BY_DATE_OF_RELEASE,
};