import React from 'react';
import NavBarBeforeLogin from './Misc/NavBarBeforeLogin';
function AboutUs() {
    return (<>
        <NavBarBeforeLogin/>
        <section className="bg-info bg-gradient">
            <div className="container py-5">
                <h1 className="text-center"> <b> About Us </b> </h1>
            </div>
        </section>
        <section className="bg-light bg-gradient">
            <div className="container py-5">
                <h5> BookCart </h5>
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Doloribus quos laudantium accusamus nam quasi, veniam vitae eaque, tempore cum magni, necessitatibus autem nihil alias deleniti ab nostrum blanditiis sint atque.
                    Culpa aperiam amet ratione, corporis aliquam porro quidem. Consequuntur fugit veritatis quam. Aspernatur voluptas ad dolorum eius tempore! Cumque eius molestias nostrum ab unde tempora consectetur doloribus sit illo numquam!
                    Assumenda, ea excepturi nulla minus vitae autem temporibus molestias qui vero, illum aspernatur! Quia, error pariatur molestiae aperiam reprehenderit eos explicabo obcaecati velit, cupiditate nulla doloribus labore! Reiciendis, vel hic.
                    Inventore omnis temporibus a quidem, provident eligendi quaerat nam laboriosam facere perferendis totam aspernatur ratione alias dicta ex dolores rerum repudiandae eveniet rem nemo at ducimus? Veniam natus eveniet ipsum?
                    Earum, perspiciatis! Minima, quibusdam inventore, sequi minus nobis officia quos iusto, tempore nesciunt modi facilis iste totam ipsam iure reiciendis voluptatum quod ex delectus laboriosam? Facere suscipit aliquam cupiditate sapiente.
                    Rerum atque officia explicabo neque vero cumque adipisci odit fugit velit aperiam expedita, quaerat reprehenderit dicta aliquam corrupti enim aspernatur veritatis eaque fugiat sint, blanditiis unde, corporis quasi! Distinctio, recusandae.
                    Expedita, dignissimos optio adipisci eos cumque dolores quae, ab quis maiores odit quibusdam necessitatibus labore animi asperiores quam voluptatibus eum nesciunt molestias reiciendis, magnam molestiae laboriosam earum exercitationem distinctio. Tenetur!
                    Corporis molestiae nulla officia qui? Nostrum itaque, hic rerum reiciendis fugiat sed nam illo incidunt quam deleniti rem, delectus corrupti temporibus eius quod error repudiandae odit eaque sit? Voluptate, unde!
                    Modi ducimus cupiditate, quidem, labore soluta molestias officia natus iure deleniti enim nam cum, eum inventore. Cupiditate cumque laboriosam eveniet laborum, sit corrupti perspiciatis enim quas suscipit ut temporibus corporis.
                    Velit suscipit eaque perspiciatis! Quisquam, nisi quas eius fuga quaerat rem nostrum incidunt blanditiis est soluta voluptatem exercitationem quo quibusdam sit eum itaque provident quis nemo mollitia, at qui quidem.
                    Rem quaerat distinctio debitis excepturi necessitatibus facilis ab accusantium obcaecati praesentium. Quibusdam hic nostrum pariatur dolores sit nihil explicabo numquam, eos totam aliquam laborum. Quam modi vitae quisquam est! Quasi.
                    Doloremque ipsa et architecto commodi assumenda alias, quasi ducimus inventore tenetur voluptate minima amet dicta fuga natus repellat! Exercitationem non eligendi ipsum repellendus nostrum optio facere inventore dolore quo earum.
                    Quae praesentium repellendus commodi provident perspiciatis eius, vel nam, vero accusantium sed voluptatibus officiis molestias rem itaque magnam nobis omnis a sequi corrupti laudantium, ut aperiam quisquam eum explicabo. Eveniet.
                    Animi ipsum autem atque assumenda minus? Iste consequatur possimus odit esse in, facere dolores accusamus? Soluta, recusandae voluptate harum, aperiam exercitationem amet quam modi obcaecati, officia sequi eaque doloribus dolore!
                    Quos impedit neque aliquam unde provident incidunt rerum, sapiente atque, repudiandae aspernatur quam praesentium saepe doloremque itaque ducimus minus, fugiat totam quo architecto ipsum laborum labore! Dignissimos cupiditate saepe ad?
                    Accusantium provident tenetur doloremque sit praesentium perspiciatis iure asperiores quasi consequatur impedit facere a vitae labore ratione pariatur fugiat natus maiores ipsam sapiente quibusdam consectetur, sequi tempore! Enim, deleniti quidem!
                    Laborum ex optio blanditiis? Aliquid modi facere cumque, inventore veritatis maiores sint nam quos tenetur at officia explicabo similique sed delectus tempore error sunt. Blanditiis nemo optio culpa quis eos.
                    Animi tempore sed eos voluptates explicabo ea ab dicta, obcaecati vero, quisquam adipisci reiciendis assumenda id quos! Possimus provident eligendi eius veniam tempore excepturi nobis aliquid! Molestiae beatae repellendus recusandae?
                    Itaque, esse quod. Praesentium vitae quas doloremque error explicabo eveniet quaerat officiis odio facilis odit libero fugit porro perspiciatis, assumenda fugiat iste, quidem velit qui corporis, amet voluptatum! Numquam, ullam.
                    Cumque quae neque magnam fugit natus tempore vitae temporibus non incidunt atque. Eligendi sunt aliquid ut, vitae repellat ratione atque nemo quaerat dolores quasi dolorem rem eos impedit porro libero.
                    Quae veritatis sit totam accusamus praesentium, dicta inventore ratione, quasi explicabo non eos fuga maiores rerum voluptatum. Iure, cupiditate voluptate reprehenderit molestias doloremque quam illo dolore libero quaerat exercitationem possimus.
                    Necessitatibus reprehenderit recusandae earum debitis provident ipsam, amet ipsum. Esse architecto perferendis enim aliquam rerum sequi, quidem quos dolor dolore facilis beatae est aliquid consequuntur voluptatem natus eius! Consequatur, quam?
                    Et ea quia accusantium a minima autem aspernatur nam delectus porro aut ducimus itaque incidunt doloremque nemo aperiam, dolorum magni reprehenderit id earum possimus error cupiditate in tempora ab! Tempora!
                    Itaque quibusdam rem et. Error eum reprehenderit ullam ut id ducimus unde necessitatibus modi laboriosam! Expedita, eius doloremque. At officiis alias architecto ad quos optio necessitatibus, expedita rem inventore vitae!
                    Nemo aut magni obcaecati sunt amet perferendis ullam? Quod quisquam quia et, temporibus reiciendis doloremque, delectus explicabo, nihil hic maxime incidunt? Itaque architecto minima, facere neque obcaecati natus error aut.
                    Consequuntur assumenda a rerum qui, amet deserunt sed, error, natus nemo excepturi adipisci explicabo eum numquam harum voluptas obcaecati sequi quae aspernatur laboriosam praesentium? Quas voluptates inventore illo hic enim?
                    Cumque labore sunt beatae a tenetur sequi sit voluptatem commodi tempore dolorem aspernatur necessitatibus dolorum mollitia, quisquam ea nulla dolor reiciendis aperiam tempora suscipit fuga? Tempore provident magnam ab earum!
                    Quidem, ad quae! Nisi iure accusamus facilis suscipit quidem ratione, mollitia et error! Cum illum sunt cupiditate cumque perferendis itaque ducimus deleniti, similique maiores asperiores repellat, repudiandae culpa doloremque aspernatur!
                    Obcaecati ad optio vero, inventore eum ex rerum accusamus tempore adipisci eius? Ipsam praesentium repudiandae quo voluptas illum libero at quia possimus magnam aperiam consectetur facere amet, dolorem, esse nam!
                    A cupiditate obcaecati ratione velit impedit reiciendis architecto omnis rerum corporis vero labore nobis, quisquam eos veniam, ea delectus quas ipsa molestias? Exercitationem repudiandae vero similique nulla aliquid nisi alias.
                    Provident doloremque recusandae tempora quas eveniet ut quo, suscipit ipsa minus odit cumque, pariatur dolorem nulla? Ad adipisci assumenda esse, doloribus sed tempore consequatur alias molestias dicta similique, commodi facilis.
                    Debitis sunt dicta error et iure dolores fuga atque, cupiditate eaque exercitationem dolorum, suscipit, itaque tempora nam consectetur. Iste facere dolorum unde cumque facilis quos ducimus, eaque libero eos laborum.
                    Nulla doloribus iste sunt maxime aliquam atque voluptas illum voluptatum suscipit et, veniam non, necessitatibus iure eos expedita? Temporibus ex excepturi ipsam debitis expedita odit fugit repellat eum dolore nostrum?
                    Distinctio, sed voluptates! Enim beatae at porro quod et autem, eum molestias voluptatum vero, quos reiciendis, sit exercitationem laudantium omnis veniam expedita a nesciunt quasi possimus veritatis? Magni, ratione amet!
                    Voluptate, commodi. Harum cumque, sapiente earum architecto neque laborum consequatur excepturi, dolorem nobis cupiditate iure aliquid numquam delectus repellat ea nihil illum asperiores perferendis consectetur error accusantium culpa voluptate id?
                    Sapiente impedit pariatur id mollitia illum optio ab corrupti aliquid cumque quaerat magni eum omnis tempore earum commodi suscipit quisquam alias quam doloremque quidem, in cupiditate. Culpa, error reiciendis. Expedita.
                    Amet molestias error dignissimos assumenda voluptate perspiciatis. Maiores nostrum pariatur impedit esse nisi dignissimos neque in nesciunt, id ea quo! Totam dicta saepe ipsum repellat molestiae quidem, quasi velit eos!
                    Harum tempore, consectetur debitis iusto dolorum eum cupiditate ipsum impedit vero et beatae eligendi neque odio sequi amet fugit earum dolor? Voluptates dolorem consequuntur repudiandae, provident sit nesciunt quidem quo!
                    Facere cum asperiores omnis rem ducimus a ex doloremque. Itaque architecto quos, quisquam repudiandae ratione sunt reiciendis beatae ullam corrupti ut, ipsum neque, natus voluptate sit magnam esse eveniet non.
                    Voluptas neque sapiente sint? Quo fuga, unde repudiandae culpa eaque vel dignissimos est laborum earum recusandae ducimus at eum obcaecati voluptates minima, autem assumenda totam omnis, quos libero inventore! Consequuntur!
                    Sunt doloribus eos culpa commodi totam quae earum praesentium ipsa, consequatur neque pariatur accusamus non nisi, sint tempore numquam explicabo sit ex facere ea error, illo voluptatem laboriosam. Pariatur, minima.
                    Facere, autem inventore debitis obcaecati magni amet et nemo labore optio harum provident? Nam ab commodi, sequi maiores saepe eveniet eaque sit animi autem perferendis recusandae magni modi eligendi optio!
                    Voluptatum facilis saepe est doloremque quaerat quod voluptatibus consequatur? Sequi molestiae quod ea molestias, nisi laudantium veniam temporibus nostrum labore voluptatem a vitae odio incidunt placeat dolorem cum beatae vero?
                    Sapiente magnam, nam a numquam repellat nisi eius vero necessitatibus libero optio soluta, delectus quisquam deserunt obcaecati reprehenderit quasi eligendi dolor rem, ipsa sunt itaque sint veritatis voluptatum omnis! Et!
                    Eum amet accusantium quas accusamus nisi aut delectus voluptatum aspernatur dolores beatae facere voluptatibus vitae ex eos earum, omnis sunt, tenetur a similique impedit possimus architecto expedita dolorem! Quis, in.
                    Dolores officia corporis hic iure omnis officiis recusandae distinctio. Iusto qui esse temporibus! Laudantium doloribus nemo perferendis doloremque rerum aliquid. Minus dolore sint pariatur ad optio sit accusamus harum suscipit?
                    Sed, atque aliquam. Repudiandae, sunt. Voluptate magnam unde porro, vero architecto perferendis quam eligendi tenetur quod ipsam, consectetur necessitatibus voluptates, totam officiis eum nesciunt harum nulla laborum sequi veritatis dolorum?
                    Reiciendis consectetur deleniti repellendus assumenda molestias at natus praesentium accusantium odio tenetur vitae eius, dolorum commodi! Laboriosam voluptatibus minus quisquam saepe ipsum dignissimos quidem perferendis labore. Eligendi quasi explicabo facere.
                    Debitis ratione nihil facilis minus, placeat soluta officiis tenetur repudiandae, non illo, voluptatibus explicabo? Ducimus, soluta officiis! Quos eius quam quod enim at exercitationem, odit dolor aliquam quis ducimus fugit.
                    Inventore maiores fugiat officiis, non mollitia earum consequatur itaque nemo dolorem reiciendis illum architecto deleniti debitis voluptatem aut, assumenda voluptate. Repellat id voluptatum alias aperiam possimus eum, amet a rerum.
                    Eum aperiam veritatis, quis recusandae quo itaque! Adipisci voluptatem magni dicta in, laboriosam ratione et officia at quia molestiae aperiam deleniti aspernatur sunt laborum. Veritatis natus eaque qui facilis dolorem.
                    Id reiciendis necessitatibus cumque a doloremque. Harum impedit repellat libero sequi aliquid tenetur reprehenderit, aspernatur repellendus nulla, eius, explicabo odio? Praesentium eligendi quibusdam repudiandae et temporibus totam id optio accusamus?
                    Mollitia sint illum placeat similique fuga illo nesciunt, est qui dolorem quod. Minima ipsum laborum doloremque. Eius perspiciatis recusandae illo, atque quos quis, architecto nisi possimus voluptatibus, animi mollitia enim.
                    Voluptatibus nam culpa, aspernatur illo facilis sapiente explicabo odit asperiores odio? Nobis repellat voluptatem ipsam sint, a quaerat ut saepe asperiores nisi incidunt fugit hic dolorem voluptatibus deleniti laudantium impedit.
                    Ad esse perspiciatis eligendi vero repudiandae fugiat architecto quae repellat voluptas modi hic fuga tenetur sequi labore optio officia, rerum recusandae, dicta rem quos illo. Ut optio officiis dolor eum!
                    Similique fugit, quam qui asperiores expedita sint quibusdam facere ad recusandae unde ratione quos officiis magnam consequatur non. Ad provident quae consequuntur temporibus, iste doloribus maxime itaque eius deserunt minima.
                    Veritatis optio facilis iure magni eveniet, quasi earum autem laboriosam, commodi quae beatae totam error vitae excepturi, nesciunt sapiente similique. Ab esse quod consequatur? Soluta quo ducimus quod totam animi?
                    Consectetur adipisci, totam delectus molestias eum ipsa aliquam ad perspiciatis nisi atque officiis fugit iste distinctio tenetur maxime, consequatur asperiores? Officiis ea praesentium ratione iste unde? Voluptates eum tenetur ab!
                    Eligendi id deserunt ipsam sunt optio nobis placeat libero maiores! Voluptates nihil quia, exercitationem perspiciatis ratione dolores facere dolore veritatis accusamus officiis officia minus minima quisquam? Suscipit laborum voluptate natus.
                    Totam quia reiciendis distinctio sequi aut, accusantium quo quos, tenetur neque possimus voluptas illo quis veritatis nemo doloremque provident, molestiae odio praesentium corrupti mollitia deserunt iste soluta. Officiis, a dolorum.
                    Odio doloribus deserunt mollitia voluptatibus necessitatibus ex laudantium dolorum rerum porro sapiente. Fugiat quo iure laborum excepturi quibusdam commodi, quam, fugit totam assumenda quasi distinctio similique perspiciatis voluptatem amet laudantium.
                    Mollitia facilis, maxime nostrum sequi consectetur totam magni amet, ab vero ipsa eum consequatur deserunt dignissimos nulla sed excepturi? Dolor impedit ad quas facere exercitationem hic, nesciunt dolore aperiam at.
                    Vel, nobis dolore accusamus provident officiis exercitationem fugit quibusdam sequi quae voluptas laudantium placeat eaque fuga amet perferendis nemo, voluptates illum reprehenderit rerum alias. Nobis iste atque fugit impedit optio.
                    Ipsam velit reiciendis magnam nihil sed ducimus cupiditate consequuntur ullam error quia maiores cum, facilis fugit eligendi. Fugit, inventore cupiditate! Minima similique repudiandae obcaecati, amet molestias rem incidunt possimus asperiores.
                    Consequatur incidunt esse deserunt quos numquam perferendis nesciunt possimus quasi eos totam soluta ut ea molestias reprehenderit, provident odio eius atque fugit temporibus nostrum nobis! Illum labore officia quibusdam enim!
                    Molestiae rerum optio obcaecati veritatis doloremque! Veniam amet magnam veritatis voluptate voluptates dolores, tempore aut, deserunt commodi deleniti pariatur cum est sed nisi quasi ab rem iste dolorum expedita ipsa.
                    Ipsam atque qui asperiores cupiditate ratione tempore voluptatibus sit dolorem dolorum? Tempora possimus quis dolorum est qui sed. Similique molestias totam nisi aut ducimus vero quibusdam. Adipisci, odio praesentium? Repudiandae!
                    Natus ipsum unde, provident possimus alias iure, temporibus doloremque adipisci at est corporis ipsa quae dolor nobis modi odit incidunt placeat, in voluptatum accusantium quam sapiente? Nobis quis suscipit libero!
                    Nostrum magni aliquid recusandae quaerat odio laborum aperiam. Possimus dolor officiis sed pariatur quidem nobis repudiandae provident maiores. Quod eaque et fugiat animi velit distinctio eligendi repudiandae earum corporis id.
                    Odit magnam officiis corporis asperiores provident mollitia at unde dolores a quibusdam quaerat iure facere doloremque soluta debitis consequatur perspiciatis voluptates error ad, ipsum ipsam enim. Inventore necessitatibus voluptates aspernatur.
                    Ex dolor iure pariatur exercitationem sapiente est facere magni, enim nisi quae fugiat aut, voluptatum tempore rerum. Officiis quam accusantium esse porro minus omnis? Quibusdam earum laborum aperiam beatae tempora.
                    Tempora odio doloribus, architecto ratione dolor quidem consequatur accusamus assumenda ducimus ea cum fuga possimus voluptatem dolorum? Eum iure provident architecto sint non dolor debitis ipsam sapiente. Porro, id. Officiis?
                    Accusamus, harum esse voluptatem hic fugiat quod ea sunt nesciunt corrupti iure iusto quisquam iste repudiandae deserunt, consectetur voluptate suscipit ipsum. Repellendus tempora, impedit velit molestias blanditiis natus nemo nobis.
                    Ea corrupti velit nisi nulla a. Eveniet consectetur amet in, provident mollitia perspiciatis sit necessitatibus odio, reiciendis iusto quo eligendi asperiores ut illum praesentium qui natus ullam expedita fugit laudantium?
                    Magnam officia at tempora, molestiae laborum mollitia unde laboriosam, cum veritatis officiis dolorum, nesciunt quaerat atque accusantium nemo ratione veniam totam repellat odio debitis fuga maiores ipsum nobis. Minus, porro.
                    Fugiat exercitationem quisquam voluptate, numquam in praesentium pariatur quod eligendi magni quidem deserunt odio ad totam maiores similique! Facere quam ab eius reprehenderit amet nemo corporis! Laboriosam maxime sit recusandae!
                    Praesentium natus quas quos accusantium excepturi! Obcaecati tempore, repellat quibusdam exercitationem eligendi ab cumque! Delectus molestiae aliquid voluptates fugit aut veniam perspiciatis, sequi asperiores iste est voluptas, consequuntur magni porro.
                    Magni eius minima voluptates quibusdam sunt odit voluptatum voluptate corporis vel ea! Fugit obcaecati assumenda illo fuga odio, commodi accusamus. Quaerat fugiat ad accusamus assumenda at illum sed expedita in!
                    Provident sunt incidunt exercitationem, qui quibusdam, odio ipsum magni eaque perspiciatis asperiores laudantium iure ullam. Aliquid laborum cumque deleniti. Voluptatum, quas illo voluptate quam sequi soluta aperiam placeat nisi sint.
                    Repudiandae provident veniam corporis optio, neque aliquid doloribus, sit eveniet eligendi, animi cupiditate a omnis quo? Dolore sint voluptatum harum laboriosam quis distinctio unde, aut aspernatur numquam sit dolores sequi!
                    Adipisci nesciunt doloribus labore voluptatem laboriosam laudantium qui ipsa exercitationem illo dicta quia distinctio ipsum dignissimos fugit dolore nulla accusantium quisquam optio corporis ad eveniet soluta, mollitia iusto. Voluptate, quos?
                    Dolore illum saepe fuga a perferendis iste ad pariatur repellendus, recusandae accusamus soluta similique assumenda hic et tempore obcaecati porro? Sunt nisi, modi a beatae excepturi facilis molestias at fugiat!
                    Ducimus aperiam ex delectus quidem. Commodi, praesentium laborum. Aut vitae voluptatibus earum at non quae, in impedit illum laborum? Doloremque dolorum expedita iure dicta! Doloribus cum deleniti ut saepe vel.
                    Illum a minima et eveniet, labore ratione? Dolorum ad quibusdam nihil accusamus aperiam vel! In maiores quisquam, tempora unde sint harum excepturi reiciendis facilis animi a quasi eum, id voluptatem.
                    Vitae, et dignissimos? Pariatur, numquam saepe ducimus officiis mollitia perspiciatis doloribus reprehenderit, deleniti quod, quasi ipsam repellendus. Aliquam ratione in suscipit facilis neque vero possimus fugiat officia id iusto. Tenetur.
                    Dicta commodi assumenda soluta, rerum veritatis ducimus. Beatae labore omnis tenetur possimus, illum corporis laborum cum illo, exercitationem soluta nostrum quasi, deleniti officia accusantium error. Aperiam maiores harum sit placeat!
                    Earum molestias molestiae, at expedita id repellendus pariatur explicabo soluta repudiandae laudantium culpa cupiditate consequatur fugit quos reiciendis ex iste cum atque quo, ullam eveniet fugiat voluptates delectus! Iusto, voluptates?
                    Nemo eligendi minus, quia, deleniti cupiditate laudantium excepturi iste totam, pariatur qui eveniet! Dignissimos nostrum veritatis eveniet adipisci quia, voluptates, quod illum quidem temporibus explicabo nihil ex, similique numquam sit.
                    Assumenda fugit illo, culpa quia, repellat, magni quis eum ipsa impedit voluptates similique sequi consequatur laborum id dignissimos nostrum sunt quisquam. Ratione beatae minima consequuntur corrupti voluptatum, sint quo repellat.
                    Nam molestiae aperiam obcaecati, impedit at iste deserunt voluptatem omnis sed ipsum provident quisquam illo, nesciunt id laudantium laborum animi magnam nostrum porro iusto quibusdam harum? Debitis molestiae voluptatibus quis.
                    Sunt nobis itaque quaerat dolore, accusantium error nemo cumque perspiciatis distinctio recusandae, consequatur illum nostrum laboriosam! Excepturi exercitationem modi optio blanditiis aperiam, quisquam recusandae voluptas similique officiis iusto tempora voluptatum.
                    Numquam laudantium aut eligendi vitae cumque nesciunt exercitationem? Sunt id omnis esse atque saepe eligendi corrupti. Rem, optio ipsum repudiandae dolorem laudantium, nemo facilis quidem necessitatibus repellendus repellat eius consectetur.
                    Aliquam odio ullam sunt. Vitae harum numquam aliquid maxime ipsum earum cumque quia eligendi sequi a quam, dignissimos deserunt magnam sit eveniet iusto assumenda doloremque ducimus amet molestiae. Eveniet, exercitationem?
                    Ex laborum quos deserunt cupiditate enim doloribus accusantium asperiores assumenda alias exercitationem, soluta eius quia, repudiandae fugiat fugit, at nemo vel rem tenetur voluptas? Illum, culpa quisquam. Consequatur, odio quo!
                    Recusandae accusamus molestias laborum nisi. Quisquam, dolor? Id obcaecati odio, quisquam, quae quia at soluta tempore, laborum quibusdam qui ad dolore vitae corrupti quam enim ratione nostrum repellendus modi alias?
                    Non voluptatum fugiat necessitatibus dolorum, placeat odit impedit. Corporis rem eius, harum qui, sint possimus, ullam voluptatem fuga voluptates suscipit assumenda quasi expedita maxime perspiciatis excepturi eligendi? Laudantium, consequatur veniam?
                    Possimus mollitia eum, commodi deleniti libero, pariatur qui nostrum dolorum doloremque eos quibusdam esse sequi magnam aspernatur? Quasi saepe voluptate quae consequuntur vero, ullam, neque impedit delectus rerum inventore tempore!
                    Neque cum sed perferendis assumenda pariatur, fugiat tempora ducimus qui voluptate deserunt possimus veritatis repellendus obcaecati adipisci dolores, quo inventore autem quam unde. Iure voluptate magnam ipsam ullam laudantium? Rem!
                    Itaque, adipisci! Nesciunt voluptates tempore sunt expedita omnis ab magni commodi aliquid sapiente ut. Incidunt iure et aut minus, a eligendi odio libero velit qui, nesciunt reiciendis hic ut modi?
                    Esse corporis beatae impedit, accusamus totam numquam quo a tenetur accusantium? Sed expedita asperiores consequuntur, laboriosam perspiciatis blanditiis? Iste ab voluptatibus rerum dolore corrupti sed asperiores ad mollitia dolor maxime.
                </p>
            </div>
        </section>
    </>);
}

export default AboutUs;